version: '3.8'
services:
  web:
    build: .
    ports:
      - "4200:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: tech-shop
      MYSQL_ROOT_PASSWORD: root  # Only set the root password
    volumes:
      - mysqldata:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d  # Mount the initialization scripts directory
    ports:
      - "3306:3306"

volumes:
  mysqldata:
